### ISSUE TITLE
Рефакторинг

### ISSUE THREAD

**Issue by eliseealex** [codex-team/codex#16]
# Epic
- [x] Перейти на использование DAO (#26, #36).
- [x] Удалить все вызовы базы из контроллеров (#20, #21).
- [x] Добавить нормальную валидацию при загрузке изображения.

Участники: @illiiiillllilii, @eliseealex.
