### ISSUE TITLE
Блок «Читайте далее» под статьей

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex#86]
- [x] добавляем блок посмотреть далее с 3 случайными ссылками на статьи #112;
- [x] оформляем и верстаем этот блок #110;
- [x] сортируем список по популярности #109;
- [ ] добавляем какие-нибудь полезные фишечки в этот блок #111;

**Comment by n0str** [comment]
Могу взять backend. Такие задачи нужно оформлять двумя issues, то слишком разные подходы.

**Comment by eliseealex** [comment]
Разбил задачу на отдельные, чтобы быстрее можно было ревьюить и мержить.

**Comment by illiiiillllilii** [comment]
Зачем прям люто рандомить?

Можно выводить:
- 2 популярных и 1 непопулярную
- 1 популярную и 2 непопулярных
- 1 популярную, 1 из серединки и 1 непопулярную
- ну или самый наглый способ — пихать самое малочитаемое
